// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// produceDistTipsAncestorsMatrixRcpp
arma::mat produceDistTipsAncestorsMatrixRcpp(uint numTips, uint numNodes, IntegerVector branchMatchIndexVec, NumericVector edgeLengthsVec, IntegerVector parentNumVec);
RcppExport SEXP _CovidCluster_produceDistTipsAncestorsMatrixRcpp(SEXP numTipsSEXP, SEXP numNodesSEXP, SEXP branchMatchIndexVecSEXP, SEXP edgeLengthsVecSEXP, SEXP parentNumVecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< uint >::type numTips(numTipsSEXP);
    Rcpp::traits::input_parameter< uint >::type numNodes(numNodesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type branchMatchIndexVec(branchMatchIndexVecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type edgeLengthsVec(edgeLengthsVecSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type parentNumVec(parentNumVecSEXP);
    rcpp_result_gen = Rcpp::wrap(produceDistTipsAncestorsMatrixRcpp(numTips, numNodes, branchMatchIndexVec, edgeLengthsVec, parentNumVec));
    return rcpp_result_gen;
END_RCPP
}
// getMRCA_Rcpp
uint getMRCA_Rcpp(IntegerVector parentNumVec, IntegerVector tipsNumVec, uint numTips);
RcppExport SEXP _CovidCluster_getMRCA_Rcpp(SEXP parentNumVecSEXP, SEXP tipsNumVecSEXP, SEXP numTipsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type parentNumVec(parentNumVecSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type tipsNumVec(tipsNumVecSEXP);
    Rcpp::traits::input_parameter< uint >::type numTips(numTipsSEXP);
    rcpp_result_gen = Rcpp::wrap(getMRCA_Rcpp(parentNumVec, tipsNumVec, numTips));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CovidCluster_produceDistTipsAncestorsMatrixRcpp", (DL_FUNC) &_CovidCluster_produceDistTipsAncestorsMatrixRcpp, 5},
    {"_CovidCluster_getMRCA_Rcpp", (DL_FUNC) &_CovidCluster_getMRCA_Rcpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_CovidCluster(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
