# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getMRCAclustersRcpp <- function(parentNumVec, childrenNumList, descendedTipsList, subtreeIndexVec, vertexRegionVec, tipNamesVec, subtreeRootNum, distTipsAncestorsMatrix, subtreeIndex, numTips, regionLabel, distLimit) {
    .Call('_CovidCluster_getMRCAclustersRcpp', PACKAGE = 'CovidCluster', parentNumVec, childrenNumList, descendedTipsList, subtreeIndexVec, vertexRegionVec, tipNamesVec, subtreeRootNum, distTipsAncestorsMatrix, subtreeIndex, numTips, regionLabel, distLimit)
}

simulateNodeTimesRcpp <- function(numTips, baseRatePerIntroduction, orderedVertices, subtreeIndexVec, tipTimes, edgeMatrix, childrenNumList, branchMatchIndexVec, parentNumVec) {
    .Call('_CovidCluster_simulateNodeTimesRcpp', PACKAGE = 'CovidCluster', numTips, baseRatePerIntroduction, orderedVertices, subtreeIndexVec, tipTimes, edgeMatrix, childrenNumList, branchMatchIndexVec, parentNumVec)
}

getSumMatRcpp <- function(clusMemVecList) {
    .Call('_CovidCluster_getSumMatRcpp', PACKAGE = 'CovidCluster', clusMemVecList)
}

